# 5 Access, Authentication and Authorization
# 5.1 Configure time-based job schedulers
- name: Check if cron is installed
  shell: echo $(rpm -q cron)
  register: cron_is_installed

- block:
  - name: show msg TODO
    debug: msg="cron is installed!!!"
# 5.1.1 Ensure cron daemon is enabled and running 
# 5.1.2 Ensure permissions on /etc/crontab are configured 
# 5.1.3 Ensure permissions on /etc/cron.hourly are configured 
# 5.1.4 Ensure permissions on /etc/cron.daily are configured 
# 5.1.5 Ensure permissions on /etc/cron.weekly are configured  380
# 5.1.6 Ensure permissions on /etc/cron.monthly are configured  .382
# 5.1.7 Ensure permissions on /etc/cron.d are configured  384
# 5.1.8 Ensure cron is restricted to authorized users 
  when: cron_is_installed.stdout.find('package cron is not installed') == -1

- name: Check if at is installed
  shell: echo $(rpm -q at)
  register: at_is_installed

- block:
# 5.1.9 Ensure at is restricted to authorized users
  - name: Ensure at is restricted to authorized users
    shell: stat /etc/at.deny
    register: at_deny

  - name: remove at.deny
    shell: rm /etc/at.deny
    when: at_deny.stdout.find('No such file or directory') == -1


  when: at_is_installed.stdout.find('package at is not installed') == -1
# 5.2 Configure SSH Server .390
- name: 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured
  shell: "stat /etc/ssh/sshd_config | grep \"Access: (\" | awk '{print $2}'"
  register: result_521


# 5.2.2 Ensure permissions on SSH private host key files are configured
# 5.2.3 Ensure permissions on SSH public host key files are configured 
# 5.2.4 Ensure SSH access is limited  398
# 5.2.5 Ensure SSH LogLevel is appropriate  .400
# 5.2.6 Ensure SSH X11 forwarding is disabled  .402
# 5.2.7 Ensure SSH MaxAuthTries is set to 4 or less  403
# 5.2.8 Ensure SSH IgnoreRhosts is enabled  404
# 5.2.9 Ensure SSH HostbasedAuthentication is disabled  .405
# 5.2.10 Ensure SSH root login is disabled  406
# 5.2.11 Ensure SSH PermitEmptyPasswords is disabled  .407
# 5.2.12 Ensure SSH PermitUserEnvironment is disabled  408
# 5.2.13 Ensure only strong Ciphers are used  409
# 5.2.14 Ensure only strong MAC algorithms are used  .412
# 5.2.15 Ensure only strong Key Exchange algorithms are used  415
# 5.2.16 Ensure SSH Idle Timeout Interval is configured  417
# 5.2.17 Ensure SSH LoginGraceTime is set to one minute or less  419
# 5.2.18 Ensure SSH warning banner is configured  .421
# 5.2.19 Ensure SSH PAM is enabled  .422
# 5.2.20 Ensure SSH AllowTcpForwarding is disabled  .424
# 5.2.21 Ensure SSH MaxStartups is configured  .426
# 5.2.22 Ensure SSH MaxSessions is limited  .427
# 5.3 Configure PAM 
# 5.3.1 Ensure password creation requirements are configured  .429
# 5.3.2 Ensure lockout for failed password attempts is configured  432
# 5.3.3 Ensure password hashing algorithm is SHA-512  .437
# 5.3.4 Ensure password reuse is limited  439
# 5.4 User Accounts and Environment 442
# 5.4.1 Set Shadow Password Suite Parameters .443
# 5.4.1.1 Ensure password expiration is 365 days or less
# 5.4.1.2 Ensure minimum days between password changes is configured
# 5.4.1.3 Ensure password expiration warning days is 7 or more
# 5.4.1.4 Ensure inactive password lock is 30 days or less
# 5.4.1.5 Ensure all users last password change date is in the past
# 5.4.2 Ensure system accounts are secured
# 5.4.3 Ensure default group for the root account is GID 0  .455
# 5.4.4 Ensure default user shell timeout is configured  .456
# 5.4.5 Ensure default user umask is configured  459
# 5.5 Ensure root login is restricted to system console (Manual) .463
# 5.6 Ensure access to the su command is restricted  464
