# nginx setup and hardening 
- name: add cache dir
  file:
    path: /opt/cache
    state: directory

- name: install packages for Nginx
  package:
    name: "{{ webserver_packages }}"
    state: latest
  
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: create base configuration file
  template:
    src: "files/nginx.conf.j2"
    dest: "/etc/nginx/conf.d/nginx.conf"
    mode: '0600'
    owner: "root"
    group: "root"
  notify: reload nginx

- name: delete unusing configuration
  file:
    path: /usr/share/nginx/modules/{{ item }}.conf
    state: absent
  loop: "{{ unused_modules }}"

- name: delete unusing modules
  file:
    path: /usr/lib64/nginx/modules/{{ item }}.so
    state: absent
  loop: "{{ unused_modules }}"
